### ISSUE TITLE
Several errors with BERT embeddings in flair 0.5

### ISSUE THREAD

**Issue by lucaventurini** [flairNLP/flair#1703]
Hello,
I've been trying to replicate some experiments I did in the past with BERT embeddings on the new 0.5 release, without success.
The only update I did to the code was to replace BertEmbeddings with the new TransformerWordEmbeddings, as as I understood this is the recommended way to proceed. The embeddings I specify are 'bert-base-multilingual-cased', but I've been tried also with distilbert and gpt2.
In commit 63aeabf9a18bdf53af3bcba5bd80f43ac717656e, I met the error specified in #1672 , invalid shape. So I tried a more recent commit to see if this was solved.
Now I'm in 3bf14fd13c3833394c7283132148261f937c0a83, which fails due to the following error:
```python
Traceback (most recent call last):
  File "train_flair.py", line 187, in <module>
    sys.exit(main(sys.argv[1:]))
  File "train_flair.py", line 182, in main
    trainer.train(args.outfolder, checkpoint=True, **hp)
  File "/opt/conda/lib/python3.6/site-packages/flair/trainers/trainer.py", line 364, in train
    loss = self.model.forward_loss(batch_step)
  File "/opt/conda/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 146, in forward_loss
    scores = self.forward(data_points)
  File "/opt/conda/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 100, in forward
    self.document_embeddings.embed(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/base.py", line 61, in embed
    self._add_embeddings_internal(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/document.py", line 369, in _add_embeddings_internal
    self.embeddings.embed(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/token.py", line 71, in embed
    embedding.embed(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/base.py", line 61, in embed
    self._add_embeddings_internal(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/token.py", line 892, in _add_embeddings_internal
    self._add_embeddings_to_sentences(batch)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/token.py", line 965, in _add_embeddings_to_sentences
    longest_sequence_in_batch: int = len(max(subtokenized_sentences, key=len))
ValueError: max() arg is an empty sequence
```
I thought it could be because of some empty sentence, but I always call `corpus.filter_empty_sentences()` before training, to be safe.
If I switch to turian embeddings, everything goes well. Is this a known issue?

**Comment by alanakbik** [comment]
@lucaventurini haven't seen this error yet. Could you provide a minimal code example to reproduce, for instance like embedding a single sentence that throws this error?

**Comment by lucaventurini** [comment]
Ok, it took me a while to find the offending sentence, but I think it has to due with newer emojis, like 🤘, and especially if the sentence is made only of these and does not contain any other token.

**Comment by alanakbik** [comment]
Ah interesting, can you paste the sentence?

**Comment by lucaventurini** [comment]
Yes. It is just "🤟".

**Comment by alanakbik** [comment]
@lucaventurini I believe this is now fixed in master! Thanks for reporting the error!

**Comment by lucaventurini** [comment]
Thank you @alanakbik for the fix! What was the error exactly? BERT did not have an embedding for this token?

**Comment by alanakbik** [comment]
Yes the BERT tokenizer ignores this token altogether, resulting in an empty sentence that was messing up the code. So with the fix now no error is thrown, but there is still no good embedding for the token. I think the RoBERTa tokenizer handles these things better!

**Comment by lucaventurini** [comment]
I don't know if I can reopen this, but I haven't solved my initial attempt, which was to replicate a training that was working in flair 0.4.

Now (I'm in commit 
ee19896ed978ed51178d9494e0b1fda9d895eb8d ) the empty sequence error has disappeared, but I still have the errors of invalid shape that are described in #1672 .

I don't know how to find the offending sentence this time, since simply calling embed on each of them works, differently from last time.
Also, I tried roberta with the same data and it works, so it's still a problem specific with BERT.

**Comment by lucaventurini** [comment]
p.s. I may add that probably I had this problem when I opened the issue as well, but since I shuffle sentences in the batch, I sometimes saw the empty sequence error, while now that that is solved I see always the invalid shape one.

**Comment by lucaventurini** [comment]
@alanakbik do you have any suggestions on a way to find the sentences that are giving this issue?

**Comment by alanakbik** [comment]
@lucaventurini the tokenization mismatch error message prints the problematic sentence. Can you paste it here?

**Comment by lucaventurini** [comment]
Unfortunately I don't see this log message.

**Comment by alanakbik** [comment]
Since this happens during embedding, can you iterate through the sentences in your corpus and embed then one-by-one? Then we know which one throws the error.

**Comment by lucaventurini** [comment]
Unfortunately not. As I said some messages above, doing this does not result in any error.

**Comment by alanakbik** [comment]
Ah hm, maybe this somehow happens due to mini-batching. Could you try embedding batch by batch to see if there are mini-batches that throw this error?

**Comment by lucaventurini** [comment]
I tried also this, but nothing, it seems it appears only during the training of a model.

**Comment by alanakbik** [comment]
Can you give me a sample of the data to reproduce, or is it proprietary?

**Comment by lucaventurini** [comment]
It's proprietary, sorry.

I see that #1724 is quite similar in syntomps : no mismatch log error, embedding single sentences works, training a model does not. So it might be the same problem, as soon as I get back to the data I'll check if I have the same characters as well. In the mean time, you might be more lucky trying to reproduce #1724 maybe?

**Comment by lucaventurini** [comment]
Hi @alanakbik ,

I have tried v0.5.1 and finally the training completed without errors!

I still have some issues in using the classifier for predictions, though:

```python
    classifier_loaded.predict(sent, multi_class_prob=True, mini_batch_size=1)
  File "/opt/conda/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 222, in predict
    scores = self.forward(batch)
  File "/opt/conda/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 99, in forward
    self.document_embeddings.embed(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/base.py", line 61, in embed
    self._add_embeddings_internal(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/document.py", line 374, in _add_embeddings_internal
    self.embeddings.embed(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/token.py", line 71, in embed
    embedding.embed(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/base.py", line 61, in embed
    self._add_embeddings_internal(sentences)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/token.py", line 897, in _add_embeddings_internal
    self._add_embeddings_to_sentences(batch)
  File "/opt/conda/lib/python3.6/site-packages/flair/embeddings/token.py", line 1053, in _add_embeddings_to_sentences
    final_embedding: torch.FloatTensor = current_embeddings[0]
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

It seems to me that this is still related to the "missing embedding" issue of this thread.

**Comment by alanakbik** [comment]
@lucaventurini interesting - are you using the same transformer embeddings as before? Can you share a minimal script to reproduce?

**Comment by lucaventurini** [comment]
I don't have a MWE to share, right now. 

I'm using 'bert-base-multilingual-cased' for this example, which in v0.4 I used to load with BertEmbeddings, and now with TransformerWordEmbeddings, which I thought would be equivalent.
