### ISSUE TITLE
TransformerWordEmbeddings  Flair Release 0.5 cannot process special characters of Twitter data

### ISSUE THREAD

**Issue by marinapollo** [flairNLP/flair#1724]
**Describe the bug**
Traceback (most recent call last):
  File "flair-POS.py", line 121, in <module>
    max_epochs=150) 
  File "/work/flair/flair/trainers/trainer.py", line 357, in train
    loss = self.model.forward_loss(batch_step)
  File "/work/flair/flair/models/sequence_tagger_model.py", line 627, in forward_loss
    features = self.forward(data_points)
  File "/work/flair/flair/models/sequence_tagger_model.py", line 662, in forward
    self.embeddings.embedding_length,
RuntimeError: shape '[32, 33, 3072]' is invalid for input of size 3240960

**To Reproduce**
     
    data_folder = '/work/Twitter_data/'
    embedding_type = 'bert-base-uncased'
    corpus: Corpus = ColumnCorpus(data_folder, columns,
                                  train_file='train-flair'
                                  test_file='test-flair',
                                  dev_file='dev-flair')
    tag_type = 'pos'

  

    tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
    embeddings = TransformerWordEmbeddings(embedding_type,fine_tune=True)#layers="-1"

    # 5. initialize sequence tagger
    tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=False
                                        )
    
    # 6. initialize trainer

    trainer: ModelTrainer = ModelTrainer(tagger, corpus)#optimizer=Adam

   
    trainer.train(path,
              learning_rate=0.1,
              embeddings_storage_mode = 'gpu',
              #mini_batch_chunk_size=2, 
              mini_batch_size=32,
              max_epochs=150) 
    

    
   

**Expected behavior**
expected training as usual with TransformerWordEmbeddings module but the error appears because TransformerWordEmbeddings module cannot process special characters of Twitter, not sure which exactly characters these are (kind of smilies and others). When used other data (not Twitter) without special characters, everything works fine.

**Environment (please complete the following information):**
 - Version flair-0.5

**Comment by alanakbik** [comment]
I believe this is already fixed in the master branch and will be part of the upcoming release.

**Comment by marinapollo** [comment]
Thank you for your answer. One more additional comment:
I saw: "GH-1703: handle emojis in BERT."
However, there are still characters that cannot be processed, not only emojis.
I also deleted some manually from the data set, but I still get the same error.

**Comment by alanakbik** [comment]
Can you try if this works in the master branch?

**Comment by marinapollo** [comment]
> Can you try if this works in the master branch?

No, it does not work. 
I removed these characters, i.e., '\ue04b', '\ue107', '\U000fe04f', '\ue411', '\ue415', '\ue139' and then everything works fine.

**Comment by alanakbik** [comment]
This is strange. The characters seem to work for me: 

```python
text = 'this is ' + u'\ue04b' + ' !'

sentence = Sentence(text)

embeddings = TransformerWordEmbeddings('bert-base-uncased')
embeddings.embed(sentence)
for token in sentence:
    print(token.embedding)
```

Does this script run for you?

**Comment by marinapollo** [comment]
> This is strange. The characters seem to work for me:
> 
> ```python
> text = 'this is ' + u'\ue04b' + ' !'
> 
> sentence = Sentence(text)
> 
> embeddings = TransformerWordEmbeddings('bert-base-uncased')
> embeddings.embed(sentence)
> for token in sentence:
>     print(token.embedding)
> ```
> 
> Does this script run for you?

yes, this script works fine for me. 
When I use TransformerDocumentEmbeddings and TextClassifier, everything works fine as well. 
However, I have these problems only when I use SequenceTagger.

**Comment by alanakbik** [comment]
@marinapollo can you update Flair? We just released 0.5.1 which hopefully fixes this.

**Comment by marinapollo** [comment]
> @marinapollo can you update Flair? We just released 0.5.1 which hopefully fixes this.

Everything works perfectly now! Thanks!
