### ISSUE TITLE
Does 'allow_long_sentences' in TransformerWordEmbeddings work the right way?

### ISSUE THREAD

**Issue by helpmefindaname** [flairNLP/flair#2418]
I am wondering how `allow_long_sentences works` in the `TransformerWordEmbeddings`

The only functional code about it is the following:

```
# encode inputs
            encoded_inputs = self.tokenizer.encode_plus(tokenized_string,
                                                        max_length=self.max_subtokens_sequence_length,
                                                        stride=self.stride,
                                                        return_overflowing_tokens=self.allow_long_sentences,
                                                        truncation=self.truncate,
                                                        )

            n_parts: int = 0

            subtokenized_sentence_splits = []
            if self.allow_long_sentences:
                # overlong sentences are handled as multiple splits
                for encoded_input in encoded_inputs['input_ids']:
                    subtokenized_sentence_splits.append(torch.tensor(encoded_input, dtype=torch.long))
                    n_parts += 1
            else:
                subtokenized_sentence_splits.append(torch.tensor(encoded_inputs['input_ids'], dtype=torch.long))
                n_parts += 1
```

My first observation is that it sets the `return_overflowing_tokens` flag which only adds additional outputs, which aren't used.

The second thing is, that the output `input_ids` is interpreted differently (it returns a list of integers truncated to the maximum sequence length).
When long sequences is turned off, a `subtokenized_sentence_split` is the list of integers
When long sequences is turend on, a `subtokenized_sentence_split` is a single integer. Ony my part, this leads to crashes `TypeError: len() of a 0-d tensor`

Do I have a misunderstanding, or is the current `allow_long_sentences` not working right?

I'm using the current master for flair https://github.com/flairNLP/flair/commit/c5bed58b024ebc2c323d405882ef5ad6c465e651 and transformers version 4.9.2

**Comment by alanakbik** [comment]
Hello @helpmefindaname yes I believe so: in our implementation, the overflowing sentences are iterated over in a for loop so that each too-long sentence is split into multiple overlapping pieces that are separately pushed through the transformer and later re-assembled. 

However, looking into the method I noticed that some of the steps we take are actually already handled by the `tokenizers` library if we adapt the method call. I just merged a PR (#2425) that refactors the method a bit and removes a few lines of code. 

Do you still get the error you mentioned? And if so could you provide a snippet to reproduce?

**Comment by helpmefindaname** [comment]
Hello @alanakbik 

This example was breaking:
```
from flair.data import Sentence
from flair.embeddings import TransformerWordEmbeddings
from torch import nn

cos = nn.CosineSimilarity(dim=0, eps=1e-10)

sent_en = Sentence(["This", "is", "a", "sentence"], language_code="en")
sent_de = Sentence(["Das", "ist", "ein", "Satz"], language_code="de")

embeddings = TransformerWordEmbeddings("xlm-mlm-ende-1024", allow_long_sentences=True)

embeddings.embed([sent_de, sent_en])
for (token_de, token_en) in zip(sent_de, sent_en):
    print(f"Similarity between '{token_de.text}' and '{token_en.text}' is {cos(token_de.embedding, token_en.embedding).item()}")
```
but worked with `embeddings = TransformerWordEmbeddings("xlm-mlm-ende-1024", allow_long_sentences=False)`

I tested it and figured, that the refactoring didn't fix the error, but changed the error message from
```
 File "<stdin>", line 1, in <module>
  File "c:\users\bened\pycharmprojects\flair\flair\embeddings\base.py", line 60, in embed
    self._add_embeddings_internal(sentences)
  File "c:\users\bened\pycharmprojects\flair\flair\embeddings\token.py", line 1027, in _add_embeddings_internal
    longest_sequence_in_batch: int = len(max(subtokenized_sentences, key=len))
  File "C:\Users\Bened\anaconda3\envs\flair\lib\site-packages\torch\_tensor.py", line 589, in __len__
    raise TypeError("len() of a 0-d tensor")
```
to
```
 File "<stdin>", line 1, in <module>
  File "c:\users\bened\pycharmprojects\flair\flair\embeddings\base.py", line 60, in embed
    self._add_embeddings_internal(sentences)
  File "c:\users\bened\pycharmprojects\flair\flair\embeddings\token.py", line 1021, in _add_embeddings_internal
    else torch.unique(batch_encoding['overflow_to_sample_mapping'], return_counts=True, sorted=True)[1].tolist()
  File "C:\Users\Bened\anaconda3\envs\flair\lib\site-packages\transformers\tokenization_utils_base.py", line 237, in __getitem__
    return self.data[item]
KeyError: 'overflow_to_sample_mapping'
```
The way it is handled, I think there is something in that specific tokenizer that doesn't align with the other transformers tokenizers

**Comment by alanakbik** [comment]
Hm yes, it looks like this tokenizer returns some old format that looks like this: https://huggingface.co/transformers/v2.10.0/main_classes/tokenizer.html

**Comment by helpmefindaname** [comment]
Okay that makes sense, thank you for pointing that out
So this issue is now closed

**Comment by Toan-it-mta** [comment]
> Hello @alanakbik
> 
> This example was breaking:
> 
> ```
> from flair.data import Sentence
> from flair.embeddings import TransformerWordEmbeddings
> from torch import nn
> 
> cos = nn.CosineSimilarity(dim=0, eps=1e-10)
> 
> sent_en = Sentence(["This", "is", "a", "sentence"], language_code="en")
> sent_de = Sentence(["Das", "ist", "ein", "Satz"], language_code="de")
> 
> embeddings = TransformerWordEmbeddings("xlm-mlm-ende-1024", allow_long_sentences=True)
> 
> embeddings.embed([sent_de, sent_en])
> for (token_de, token_en) in zip(sent_de, sent_en):
>     print(f"Similarity between '{token_de.text}' and '{token_en.text}' is {cos(token_de.embedding, token_en.embedding).item()}")
> ```
> 
> but worked with `embeddings = TransformerWordEmbeddings("xlm-mlm-ende-1024", allow_long_sentences=False)`
> 
> I tested it and figured, that the refactoring didn't fix the error, but changed the error message from
> 
> ```
>  File "<stdin>", line 1, in <module>
>   File "c:\users\bened\pycharmprojects\flair\flair\embeddings\base.py", line 60, in embed
>     self._add_embeddings_internal(sentences)
>   File "c:\users\bened\pycharmprojects\flair\flair\embeddings\token.py", line 1027, in _add_embeddings_internal
>     longest_sequence_in_batch: int = len(max(subtokenized_sentences, key=len))
>   File "C:\Users\Bened\anaconda3\envs\flair\lib\site-packages\torch\_tensor.py", line 589, in __len__
>     raise TypeError("len() of a 0-d tensor")
> ```
> 
> to
> 
> ```
>  File "<stdin>", line 1, in <module>
>   File "c:\users\bened\pycharmprojects\flair\flair\embeddings\base.py", line 60, in embed
>     self._add_embeddings_internal(sentences)
>   File "c:\users\bened\pycharmprojects\flair\flair\embeddings\token.py", line 1021, in _add_embeddings_internal
>     else torch.unique(batch_encoding['overflow_to_sample_mapping'], return_counts=True, sorted=True)[1].tolist()
>   File "C:\Users\Bened\anaconda3\envs\flair\lib\site-packages\transformers\tokenization_utils_base.py", line 237, in __getitem__
>     return self.data[item]
> KeyError: 'overflow_to_sample_mapping'
> ```
> 
> The way it is handled, I think there is something in that specific tokenizer that doesn't align with the other transformers tokenizers


hi, have you solved this problem? If so, can you tell me how to solve it?

**Comment by SylvainVerdy** [comment]
have you find any solution ? @alanakbik thanks
