### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add_tag'

### ISSUE THREAD

**Issue by jainayush007** [flairNLP/flair#588]
Hi,

I ran the below from the first tutorial and got error- 

print(sentence[29]).add_tag('ner', 'Designation')

AttributeError: 'NoneType' object has no attribute 'add_tag'

I already imported Sentence and SequenceTagger. What else needs to be imported to make this work? I followed the script as was given on the tutorial.

**Comment by stefan-it** [comment]
I think the bracket after sentence is wrong, try to usw this Commando:

```python
print(sentence[29].add_tag('ner', 'Designation'))
```

**Comment by jainayush007** [comment]
Still the  error. I tried this as well - 
sentence[29].add_tag('ner', 'Designation')

Got below -
AttributeError: 'list' object has no attribute 'add_tag'

**Comment by jainayush007** [comment]
One question - is there a simple way to tag multiple tokens in a single command, like -
Token: 30 John
Token: 31 Campbell
Token: 32 Peterson 

--> sentence[29:31].add_tag('ner', 'Name')
or each token has to be separately tagged?

**Comment by alanakbik** [comment]
Hello @jainayush007 we currently do not have a convenience method for this, but this is something we could add in the future!

Did you solve your first issue? If not, could you post a full code example (including sentence initialization) that throws this error?

**Comment by jainayush007** [comment]
Hi Akbik,

Thanks for your response. Yeah, the first issue is resolved, i realize the
error was due to trying to apply tagging to multiple tokens.

Another question, is there a way to create a raw markup of the tagging? I
have used displacy for raw markups with spacy in the past. Can you please
share an example pls.

Thanks,
Ayush Jain

**Comment by alanakbik** [comment]
Hello @jainayush007 glad that the first issue is resolved.

The second question I don't fully understand. What do you mean by raw markup? (I am not familiar with displacy) Could you post a full example to help us better understand?

**Comment by jainayush007** [comment]
![1_7dkqpu3e-e9yknyw9c7vcq](https://user-images.githubusercontent.com/31528721/53878367-b245ba00-4031-11e9-87c5-9c92937389f9.png)

Here is an example

**Comment by alanakbik** [comment]
Thanks - but unfortunately I still don't understand the question. Could you go into more detail in what you want to do with displacy and flair?
